export const GAME_STATE_INIT = 'GAME_STATE_INIT';
export const GAME_STATE_PLAYING = 'GAME_STATE_PLAYING';
export const GAME_STATE_LOSE = 'GAME_STATE_LOSE';
export const GAME_STATE_PAUSE = 'GAME_STATE_PAUSE';